### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by dbohdan** [liveviews/liveviews#23]
At the moment I can't maintain this list. I would like someone to take over, preferably someone already maintaining a similar kind of list. How to handle it will be up to you. You will be given contributor (commit) access. Comment on this issue if you are interested.

**Comment by dlederle** [comment]
🖐️ I'm interested.

Thanks for maintaining this, its been useful / interesting to watch these all pop up over the last few years. I would like to keep the list going.

**Comment by dbohdan** [comment]
@dlederle You're welcome! I'm happy to hear you got something out of the list.

I've looked at your profile. I don't see you maintaining similar lists, but let's try this. I am sending you an invite. Accept it, and you can start working on the repo when you are ready.

**Comment by dlederle** [comment]
Thanks!

**Comment by dbohdan** [comment]
@dlederle Are you still interested in working on this list? If not, I'll reopen the issue.

**Comment by dlederle** [comment]
@dbohdan no I have not kept this up at all, apologies.

**Comment by dbohdan** [comment]
All right. I'll pin this issue.

**Comment by beenotung** [comment]
I am not actively exploring new alternatives often but I can help to review pull request (to filter out spam just in case)

**Comment by dbohdan** [comment]
@beenotung Thanks for your offer. While my health (the reason I started looking for maintainers) has improved enough that I can work on GitHub projects, I appreciate help. I'll send you a contributor invite.

**Comment by beenotung** [comment]
@dbohdan Good to hear you're recovering :)

**Comment by dbohdan** [comment]
@beenotung :-)

Okay, I can close the issue.
